" Plugin
call plug#begin()
  Plug 'crusoexia/vim-monokai'
  Plug 'editorconfig/editorconfig-vim'
  Plug 'tpope/vim-surround'
  Plug 'vim-scripts/FuzzyFinder'
  Plug 'vim-scripts/L9'

  if has('python3')
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
    Plug 'Shougo/deoplete.nvim'
  else
    Plug 'vim-scripts/AutoComplPop'
  endif
call plug#end()

" Color
syntax on
colorscheme monokai

" Visual
set noerrorbells
set visualbell
set number
set showcmd
set incsearch
set scrolloff=5

" Misc
filetype plugin on
autocmd QuickfixCmdPost make,grep,grepadd,vimgrep copen

let g:deoplete#enable_at_startup = 1
